import { FormEvent, useState } from 'react';
import styles from './ChatWidget.module.css';

type Message = { role: 'user' | 'assistant'; content: string };
const greeting = "Hi, I'm your HR assistant. Ask me about leave, payroll, or policies.";

export function ChatWidget() { const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: greeting }]);
  async function send(event?: FormEvent) { event?.preventDefault(); const message = input.trim(); if (!message || loading) return; const next = [...messages, { role: 'user' as const, content: message }]; setMessages(next); setInput(''); setLoading(true); try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message, history: messages }) }); const data = await response.json(); setMessages([...next, { role: 'assistant', content: data.reply ?? 'I could not answer that right now.' }]); } catch { setMessages([...next, { role: 'assistant', content: 'The HR assistant is temporarily unavailable. Please try again shortly.' }]); } finally { setLoading(false); } }
  return <><button className={styles.launcher} onClick={() => setOpen(true)} aria-label="Open HR assistant"><span className={styles.spark}>✦</span>Ask HR</button>{open && <section className={styles.chatWindow} aria-label="HR assistant chat"><header className={styles.chatHeader}><div><span className={styles.chatEyebrow}>PEOPLEHUB ASSISTANT</span><strong>How can I help?</strong></div><button className={styles.close} onClick={() => setOpen(false)} aria-label="Close chat">×</button></header><div className={styles.messages}>{messages.map((item, index) => <div className={`${styles.message} ${item.role === 'user' ? styles.userMessage : styles.assistantMessage}`} key={`${item.role}-${index}`}><span>{item.content}</span></div>)}{loading && <div className={`${styles.message} ${styles.assistantMessage}`}><span className={styles.typing}><i /><i /><i /></span></div>}</div><form className={styles.chatForm} onSubmit={send}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about HR..." aria-label="Message" /><button type="submit" disabled={loading || !input.trim()} aria-label="Send message">↑</button></form></section>}</>;
}
