import { FormEvent, useState } from 'react';
import leaveRequests from '../data/leaveRequests.json';
import styles from './Pages.module.css';

export function Leave() {
  const [submitted, setSubmitted] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
  return <div className={styles.page}><div className={styles.pageIntro}><div><p className={styles.eyebrow}>Time away</p><h2>Leave requests</h2><p className={styles.subtitle}>Plan time away and keep track of your team&apos;s requests.</p></div><button className={styles.primaryButton} onClick={() => document.getElementById('request-leave')?.scrollIntoView({ behavior: 'smooth' })}>+ Request leave</button></div><div className={styles.tableWrap}><div className={styles.tableHeader}><div><h3>Request history</h3><span className={styles.muted}>Your recent time away requests</span></div><span className={styles.countPill}>{leaveRequests.length} requests</span></div><div className={styles.tableScroll}><table><thead><tr><th>Request</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th>Submitted</th></tr></thead><tbody>{leaveRequests.map((request) => <tr key={request.id}><td><strong>{request.id}</strong><span>{request.employee}</span></td><td>{request.type}</td><td>{request.dates}</td><td>{request.days}</td><td><span className={`${styles.status} ${request.status === 'Approved' ? styles.approved : styles.pending}`}>{request.status}</span></td><td className={styles.muted}>{request.submitted}</td></tr>)}</tbody></table></div></div><section className={styles.formSection} id="request-leave"><div><p className={styles.eyebrow}>Make a plan</p><h3>Request leave</h3><p className={styles.muted}>Your manager will review this request.</p></div><form className={styles.leaveForm} onSubmit={submit}><label>Leave type<select defaultValue="Annual leave"><option>Annual leave</option><option>Personal day</option><option>Sick leave</option></select></label><label>Start date<input type="date" required /></label><label>End date<input type="date" required /></label><label className={styles.fullField}>Note (optional)<textarea placeholder="Add context for your manager..." rows={3} /></label><div className={styles.formActions}><button type="submit" className={styles.primaryButton}>Submit request</button>{submitted && <span className={styles.success}>Request submitted for review.</span>}</div></form></section></div>;
}
